complete --command jj --no-files --condition __fish_use_subcommand --arguments jjn --description "Create new change"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjnd --description "Create new change on develop"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjnm --description "Create new change on main"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jje --description "Edit a change"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjs --description "Show status"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjf --description "Search in log"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjdm --description "Describe change with message"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjr --description "Resolve conflicts"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjrd --description "Rebase onto develop"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjrb --description "Rebase from source"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjrbd --description "Rebase from source onto develop"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jja --description "Abandon a change"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjh --description "Edit head of working copy"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jju --description "Undo last operation"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjgf --description "Git fetch"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjgp --description "Git push"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjba --description "Advance bookmark"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjbc --description "Create a bookmark"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjbt --description "Track a bookmark"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjbu --description "Untrack a bookmark"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjbf --description "Forget a bookmark"
complete --command jj --no-files --condition __fish_use_subcommand --arguments jjbl --description "List bookmarks"
